name: Tag/Build/Publish RELEASE

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitHub project
        uses: actions/checkout@v2

      - name: Set up AdoptOpenJDK 11
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11

      - name: Set variables
        id: set-variables
        run: |
          echo ::set-output name=GITHUB_USERNAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $1}')

      - name: Publish to GitHub Packages
        run: |
          mvn deploy \
            -DskipTests \
            -s settings.xml \
            --no-transfer-progress
        env:
          GITHUB_USERNAME: ${{ steps.set-variables.outputs.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
